Modify Logic to Check Supported DRM
doverunner/html5-player-drm-samples pull request #6
Opened 2022-07-11 08:00 UTC by jiwoon-jang

2022-07-11 08:29 UTC, nykim0402 requested changes

2022-07-11 08:29 UTC, nykim0402 commented on js/videojs-sample.js
> +
p3. 불필요한 엔터는 지양해주세요  
파악하기 어렵다면, 주석을 추가해서 보는 것도 한 방법입니다~

2022-07-11 08:29 UTC, nykim0402 commented on js/videojs-sample.js
> +            playerConfig.keySystemOptions = [];
p3. `playerConfig` 를 하나로 표현할 수 있을 것 같은데 어떻게 생각하나요?
```javascript
playerConfig = {
    ... ,
    keySystemOptions: [{
        name, options, 
    }]
};
```

2022-07-12 00:58 UTC, nykim0402 approved these changes

2022-07-12 06:57 UTC, pallycon-cancel83 approved these changes

2022-07-12 08:45 UTC, closed without merging